# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "defaults"
      "size=2G"
      "mode=755"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9785-FD6C";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/3c49b6c2-81c4-4d45-ad26-d183b6b6b414";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/etc" = {
    device = "/dev/disk/by-uuid/3c49b6c2-81c4-4d45-ad26-d183b6b6b414";
    fsType = "btrfs";
    options = [ "subvol=etc" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/3c49b6c2-81c4-4d45-ad26-d183b6b6b414";
    fsType = "btrfs";
    options = [ "subvol=log" ];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/3c49b6c2-81c4-4d45-ad26-d183b6b6b414";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/3c49b6c2-81c4-4d45-ad26-d183b6b6b414";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/1e1b8a1a-7d74-4718-83e2-528c1e3cd450"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
