# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &a99r50 age1wl3q2rgk9lur8vwjlsg0jxj8hdmfvmluu3wh4cm507njfslxmdnqu4e765
  - &a99r50_klchen age15wcua828lr3rkpewrjkwuh86009x0g65czw6t0ce4rawpc2k3elquvex44
  - &i12400 age1r5m2r8vez2wkcq47dhmu00d6f5qcjx4w9eq6k9rpk46a46wn45us45ez2k
  - &i12400_klchen age1cfcz9scgrz6ennazjqha0548djg9t89xatqy3fs68dw636rgxdvqe4tm3q
  - &mbp_m1_klchen age1u2shmtyyk7hfwas3rzwde33jnjukv6nu3g3yjylyj7ek5mc5fstq43tptn
  - &sanjiao_klchen age1fdjuj7mu2n447hfpxtszs42ph6dj3fnhznyq2qerxfhhkjwney2qktpfn7
  - &a2700 age1q47sqw29xz2qd8ynhk98kchmdnrrgqap7mqnrfuezd2gurc2qvasvvgy09
  - &a2700_klchen age1kwchxh620nefj5vyq87g77cfsz56l33v4j3ps2eclz9qws5sqgqsy5g4n6
creation_rules:
  - path_regex: secrets/klchen/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *a99r50 
      - *a99r50_klchen
      - *i12400
      - *i12400_klchen
      - *mbp_m1_klchen
      - *sanjiao_klchen
      - *a2700
      - *a2700_klchen
