# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &a99r50 age16w26krhg9k43nr2hnftzjldjuyap0wsmnr2kayj255fqm7te25ks4skjkv
  - &a99r50_klchen age1j9kp2agklhtqct7mmvvavztveffqx9ghpnj7r0ptslu6qp5m8dfseka9pe
creation_rules:
  - path_regex: secrets/klchen/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *a99r50_klchen